name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  riscv-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install verilator radare2
          pip install cocotb
      - name: Test
        run: |
          git submodule update --init --depth 1
          sbt run
          cd cocotb
          export PATH=~/.local/bin:$PATH # cocotb
          ./test.sh
